name: moondream_api
description: Dart client for Moondream Vision Language Model API
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  test: ^1.25.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9
  lints: ^3.0.0
